### ISSUE TITLE
Add stats & collection info for other boundaries being mapped

### ISSUE THREAD

**Issue by DaCor1** [osmie/osm-irish-townlands#89]
Examples

LEA's
District Councils (NI Only)
Constituency 

Would it be an idea to separate historical (Townland, CP, Barony & ED) from political/administrative (county, lea etc) on to separate pages maybe?

**Comment by rory** [comment]
Good idea! What are they tagged as?

**Comment by DaCor1** [comment]
Not sure which tags you want, so here are links to examples of each

LEA - http://www.openstreetmap.org/relation/4750989 
Constituency - http://www.openstreetmap.org/relation/5146593
District Council - http://www.openstreetmap.org/relation/4183318

**Comment by IrlJidel** [comment]
Some of the tagging is in http://maps.openstreetmap.ie/josm/irishboundaries.xml
